version: '3.8'

services:
  clientvalidation:
    image: ${DOCKER_REGISTRY-}clientvalidation
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clientvalidation
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    volumes:
      - ./Resources:/app/Resources:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - clientvalidation-network
    restart: unless-stopped

networks:
  clientvalidation-network:
    driver: bridge
